# docker stack deploy -c docker-compose.yml spark_cluster
# docker stack services spark_cluster
# docker stack rm spark_cluster

version: "3.9"

services:
    master:
        build:
            context: ./
            dockerfile: ./master.dockerfile
        image: salvacorts/spark-master
        user: spark
        ports:
            - "7077:7077"
            - "8080:8080"
        networks:
            - cluster
        volumes:
            - ..:/workspace

    worker:
        build:
            context: ./
            dockerfile: ./worker.dockerfile
        user: spark
        command: -c 2 -m 3072M
        environment:
            - SPARK_MASTER=spark://master:7077
        depends_on:
            - master
        deploy:
            replicas: 4
        networks:
            - cluster
        volumes:
            - ..:/workspace

    # Auxiliar containers
    # Attach: docker attach <container name, use dockr ps>
    shell:
        image: salvacorts/spark-base
        user: spark
        environment:
            - SPARK_MASTER=spark://master:7077
        networks:
            - cluster
        volumes:
            - ..:/workspace

networks:
    cluster:
